#!/bin/bash

#conda install -c conda-forge librosa -y
#
pip install --upgrade pip
pip install --upgrade ipywidgets
jupyter nbextension enable --py --sys-prefix widgetsnbextension

pip install jp_proxy_widget
#pip install jp_proxy_widget webrtcvad scipy audiosegment

jupyter nbextension install --py --symlink --sys-prefix jp_proxy_widget
jupyter nbextension enable --py --sys-prefix jp_proxy_widget
